# Generated by Django 3.1.4 on 2020-12-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('company', models.TextField(max_length=500)),
                ('career', models.TextField(max_length=500)),
            ],
        ),
    ]
