# Generated by Django 3.1.4 on 2020-12-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SematicUi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=250)),
                ('career', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Active_item',
        ),
    ]
